---
title: "Readme"
output: html_document
date: "`r Sys.Date()`"
author: 
 - Mohsen Sadatsafavi 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Readme file for the code underlying the analysis for paper "Non-parametric inference on calibration of predicted risks"


* The core functions are under the cumulcalib R package (https://github.com/msadatsafavi/cumulcalib). Please install the development version of the cumulcalib package (e.g., via remotes::install_github("https://github.com/msadatsafavi/cumulcalib"))

* The case study results can be reproduced by running the case_study.R file. 
 
  + Note that this study needs the voipred package to access the gusto data. Please install the development version of the cumulcalib package (e.g., via remotes::install_github("https://github.com/resplab/voipred"))

  + The case_study.qmd markdown file will generate all the results of the case study.

* The simulations.R file contains the code for all simulations.
  + res <- sim_null_behavior(); process_sim_null_behavior() will generate simulation results for the null behavior of the tests.
  
  + res <- detailed_sim_linear; process_detailed_sim_results_graph(res) will generate simulations results for the linear miscalibration setup
  
  + res <- detailed_sim_power; process_detailed_sim_results_graph(res) will generate simulations results for the power miscalibration setup
  
  
